#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch relay1;
  CloudSwitch relay2;
  CloudSwitch relay3;
  CloudSwitch relay4;
  CloudSwitch relay5;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
int Relay1=5;
int Relay2=4;
int Relay3=14;
int Relay4=12;
int Relay5=13;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  pinMode(Relay1,OUTPUT);
  pinMode(Relay2,OUTPUT);
  pinMode(Relay3,OUTPUT);
  pinMode(Relay4,OUTPUT);
  pinMode(Relay5,OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
}



/*
  Since Relay1 is READ_WRITE variable, onRelay1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay1Change()  {
  // Add your code here to act upon Relay1 change
    if(relay1)
  {
    digitalWrite(Relay1,LOW);
  }
  else
  {
    digitalWrite(Relay1,HIGH);
  }
}

/*
  Since Relay2 is READ_WRITE variable, onRelay2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay2Change()  {
  // Add your code here to act upon Relay2 change
    if(relay2)
  {
    digitalWrite(Relay2,LOW);
  }
  else
  {
    digitalWrite(Relay2,HIGH);
  }
}

/*
  Since Relay3 is READ_WRITE variable, onRelay3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay3Change()  {
  // Add your code here to act upon Relay3 change
    if(relay3)
  {
    digitalWrite(Relay3,LOW);
  }
  else
  {
    digitalWrite(Relay3,HIGH);
  }
}

/*
  Since Relay4 is READ_WRITE variable, onRelay4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay4Change()  {
  // Add your code here to act upon Relay4 change
    if(relay4)
  {
    digitalWrite(Relay4,LOW);
  }
  else
  {
    digitalWrite(Relay4,HIGH);
  }
}

/*
  Since Relay5 is READ_WRITE variable, onRelay5Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay5Change()  {
  // Add your code here to act upon Relay5 change
    if(relay5)
  {
    digitalWrite(Relay5,LOW);
  }
  else
  {
    digitalWrite(Relay5,HIGH);
  }
}



